# Generated by Django 4.0.5 on 2022-06-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favorite_color', models.CharField(choices=[('Blue', 'Blue'), ('Teal', 'Teal'), ('Cyan', 'Cyan'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Red', 'Red'), ('Purple', 'Purple'), ('Chartreuse', 'Chartreuse'), ('Salmon', 'Salmon'), ('Orange', 'Orange'), ('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=50)),
                ('number_coconuts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('King', 'King'), ('Knight', 'Knight'), ('Squire', 'Squire'), ('Patsy', 'Patsy'), ('Frenchman', 'Frenchman'), ('Enchanter', 'Enchanter'), ('Commoner', 'Commoner')], default='Commoner', max_length=50)),
                ('favorite_color', models.CharField(choices=[('Blue', 'Blue'), ('Teal', 'Teal'), ('Cyan', 'Cyan'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Red', 'Red'), ('Purple', 'Purple'), ('Chartreuse', 'Chartreuse'), ('Salmon', 'Salmon'), ('Orange', 'Orange'), ('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=50)),
                ('age', models.IntegerField()),
                ('quest', models.CharField(blank=True, max_length=200, null=True)),
                ('quest_complete', models.BooleanField(default=False)),
                ('assigned_companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.companion')),
            ],
        ),
    ]
